from PyQt5 import QtCore, QtWidgets, QtSql
import sys

def addRecord():
    stm.insertRow(stm.rowCount())

def delRecord():
    stm.removeRow(tv.currentIndex().row())
    stm.select()

app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QWidget()
window.setWindowTitle("QRelationalSqlTableModel")
con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
con.setDatabaseName('hl.db3')
con.open()
stm = QtSql.QSqlRelationalTableModel(parent=window)
stm.setTable('library')
stm.setSort(1, QtCore.Qt.AscendingOrder)
# Задаем для поля категории связь с таблицей списка категорий
stm.setRelation(10, QtSql.QSqlRelation('author_name', 'author_secondname', 'author_otchestvo', 'name_book', 'book_yearprint' ,'publishing', 'locate_storage', 'on_storage', 'quarcode_add', 'date_bookadd'))
stm.select()
stm.setHeaderData(1, QtCore.Qt.Horizontal, 'Имя')
stm.setHeaderData(2, QtCore.Qt.Horizontal, 'Фамилия')
stm.setHeaderData(3, QtCore.Qt.Horizontal, 'Отчество')
stm.setHeaderData(4, QtCore.Qt.Horizontal, 'Название книги')
stm.setHeaderData(5, QtCore.Qt.Horizontal, 'Год издания')
stm.setHeaderData(6, QtCore.Qt.Horizontal, 'Издательство')
stm.setHeaderData(7, QtCore.Qt.Horizontal, 'Место в библиотеке')
stm.setHeaderData(8, QtCore.Qt.Horizontal, 'На месте ли книги')
stm.setHeaderData(9, QtCore.Qt.Horizontal, 'QR')
stm.setHeaderData(10, QtCore.Qt.Horizontal, 'Дата добавления')
#stm.setHeaderData(11, QtCore.Qt.Horizontal, 'Категория')
vbox = QtWidgets.QVBoxLayout()
tv = QtWidgets.QTableView()
tv.setModel(stm)
tv.hideColumn(0)
tv.setColumnWidth(1, 150)
tv.setColumnWidth(2, 60)
tv.setColumnWidth(3, 150)
vbox.addWidget(tv)
btnAdd = QtWidgets.QPushButton("&Добавить запись")
btnAdd.clicked.connect(addRecord)
vbox.addWidget(btnAdd)
btnDel = QtWidgets.QPushButton("&Удалить запись")
btnDel.clicked.connect(delRecord)
vbox.addWidget(btnDel)
window.setLayout(vbox)
window.resize(820, 850)
window.show()
sys.exit(app.exec_())